<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS0169;CS0414;CS0649</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CodingExercises.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.NonGeneric" Version="4.3.0" />
  </ItemGroup>

</Project>
